# Generated by Django 2.1 on 2018-12-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolStudents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='grade_name',
            field=models.CharField(choices=[('Class 1', '1'), ('Class 2', '2'), ('Class 3', '3'), ('Class 4', '4'), ('Class 5', '5'), ('Class 6', '6'), ('Class 7', '7'), ('Class 8', '8'), ('Class 9', '9'), ('Class 10', '10'), ('Class 11', '11'), ('Class 12', '12')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='grade_name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('Class I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=10, unique=True),
        ),
    ]
