# Generated by Django 2.1 on 2019-01-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('SchoolStudents', '0002_remove_userprofile_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
