# Generated by Django 2.1 on 2019-01-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TRUEFALSE', 'True/False'), ('FILLINBLANKS', 'Fill in the blanks'), ('MATCHTHEFOLLOWING', 'Match the Following'), ('COMPREHENSION', 'Comprehension')], max_length=50, unique=True),
        ),
    ]
