# Generated by Django 2.1 on 2019-01-06 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuestionBank', '0005_auto_20190105_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_answer',
            name='auth_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='question_answer',
            unique_together={('question', 'answer')},
        ),
    ]
