# Generated by Django 2.1 on 2019-01-06 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuestionBank', '0006_auto_20190106_0905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question_answer',
            unique_together={('question', 'answer', 'auth_user')},
        ),
    ]
